### ISSUE TITLE
Not able to use Easy Place when Missing Block in Schematic Verifier mode.

### ISSUE THREAD

**Issue by Romeotb** [maruohon/litematica#192]
When using Verifier rendering, I'm unable to use Easy Place Mode, Wrong blocks seems to be still working. Constantly switching on and off the Verifier GUI to enable the Easy Place Mode. Is this a bug or something wrong with my installation?

**Comment by maruohon** [comment]
It's a bug with the ray tracing code, the verifier overlay hits are used even for uses which it shouldn't be, such as the Easy Place mode. I'm not sure if I already fixed this in 1.12.2, if not, then it's somewhere on my TODO list.

**Comment by yLordMagnus** [comment]
Still an issue on version **0.0.0-dev.20201225.203013** that is from 4 days ago (Minecraft version 1.16.4).

**Comment by maruohon** [comment]
These are issues that affected all the mod on all MC versions, so I rarely fix those just for the latest version. This has been fixed in 1.12.2 a while back, as well as various other issues, but that code still hasn't been ported to the later MC versions. The next update will hopefully happen at some point in late January to February or so.
