### ISSUE TITLE
Litematica+gm3+end portal breaks F3 menu

### ISSUE THREAD

**Issue by SunSerega** [maruohon/litematica#68]
https://youtu.be/BUdXe-5jx-8

**Comment by maruohon** [comment]
This might be fixed by this commit: 7242a40bdab984d516ebdafe88a87e0b175cd8ad but I have to test it before and after that commit in this scenario.

**Comment by SunSerega** [comment]
Yeah btw, looks pretty fixed in 1.15.2:

![2020-05-23_22 19 02](https://user-images.githubusercontent.com/27270190/82738833-6c166c80-9d43-11ea-82bb-56d39c1d91ed.png)

If it's fixed in 1.15 - it means it fixed everywhere, right? Or it may still be broken on other mod-loaders?

**Comment by maruohon** [comment]
Well 1.15+ rendering changed a bunch from earlier so that may have affected this, or maybe I have the fix cherry-picked there, I can't remember. Pretty sure it's not fixed in 1.13.2 at least, probably not in 1.14.4 yet either, since the 1.12 code still hasn't been merged yet.
